// Central data file for Floren prototype content
// Based on real content from floren.nl

export const branches = [
  {
    title: 'Geestelijke gezondheidszorg',
    shortTitle: 'GGZ',
    slug: 'geestelijke-gezondheidszorg',
    description: 'Leeroplossingen voor professionals in de geestelijke gezondheidszorg. Van psychiatrische ziektebeelden tot behandelmethoden.',
    solutionCount: 14,
    category: 'cure' as const,
    image: '/images/photos/branch-ggz.jpg',
  },
  {
    title: 'Gehandicaptenzorg',
    shortTitle: 'Gehandicaptenzorg',
    slug: 'gehandicaptenzorg',
    description: 'Praktijkgerichte kennis voor begeleiders en zorgprofessionals in de gehandicaptenzorg.',
    solutionCount: 9,
    category: 'care' as const,
    image: '/images/photos/branch-gehandicaptenzorg.jpg',
  },
  {
    title: 'Thuiszorg',
    shortTitle: 'Thuiszorg',
    slug: 'thuiszorg',
    description: 'Kennis en vaardigheden voor wijkverpleegkundigen, verzorgenden en thuiszorgmedewerkers.',
    solutionCount: 18,
    category: 'care' as const,
    image: '/images/photos/branch-thuiszorg.jpg',
  },
  {
    title: 'Verpleging & Verzorging',
    shortTitle: 'V&V',
    slug: 'verpleging-verzorging',
    description: 'Leeroplossingen voor verpleegkundigen en verzorgenden in VVT-organisaties.',
    solutionCount: 22,
    category: 'care' as const,
    image: '/images/photos/branch-vv.jpg',
  },
  {
    title: 'Ziekenhuis',
    shortTitle: 'Ziekenhuis',
    slug: 'ziekenhuis',
    description: 'Voor MSZ en academische centra. Klinisch redeneren, acute zorg en verpleegtechniek.',
    solutionCount: 16,
    category: 'cure' as const,
    image: '/images/photos/branch-ziekenhuis.jpg',
  },
  {
    title: 'Zorgonderwijs',
    shortTitle: 'Zorgonderwijs',
    slug: 'zorgonderwijs',
    description: 'Lesmateriaal en leeroplossingen voor mbo- en hbo-zorgopleidingen.',
    solutionCount: 11,
    category: 'onderwijs' as const,
    image: '/images/photos/branch-onderwijs.jpg',
  },
]

export type SolutionType = 'platform' | 'e-learning' | 'consultancy' | 'tool'
export type Doelgroep = 'organisatie' | 'professional' | 'student'
export type CheckoutType = 'subscription' | 'plan' | 'contact'

export const doelgroepen = [
  { key: 'alle' as const, label: 'Alle' },
  { key: 'organisatie' as const, label: 'Organisatie' },
  { key: 'professional' as const, label: 'Professional' },
  { key: 'student' as const, label: 'Student' },
]

export const solutions = [
  {
    title: 'ZorgPad Professional',
    subtitle: 'Praktijkgerichte bij- en nascholing',
    slug: 'zorgpad-professional',
    type: 'e-learning' as SolutionType,
    tag: 'ZorgPad Professional',
    description: 'Meer dan 600 leerpaden voor zorgprofessionals van niveau 1 t/m 6. Praktijkgericht, evidence-based en afgestemd op nationale richtlijnen.',
    branches: ['Geestelijke gezondheidszorg', 'Gehandicaptenzorg', 'Thuiszorg', 'Verpleging & Verzorging', 'Ziekenhuis', 'Zorgonderwijs'],
    image: '/images/photos/solution-elearning.jpg',
    doelgroepen: ['professional', 'organisatie'] as Doelgroep[],
    checkoutType: 'subscription' as CheckoutType,
  },
  {
    title: 'ZorgPad Plug & Play',
    subtitle: 'Direct inzetbaar in jouw LMS',
    slug: 'zorgpad-plug-and-play',
    type: 'e-learning' as SolutionType,
    tag: 'ZorgPad Plug & Play',
    description: 'Dezelfde kwaliteitsinhoud als ZorgPad Professional, maar dan direct inzetbaar in je eigen LMS/LXP via SCORM of LTI.',
    branches: ['Gehandicaptenzorg', 'Thuiszorg', 'Verpleging & Verzorging', 'Ziekenhuis'],
    image: '/images/photos/care-equipment.jpg',
    doelgroepen: ['organisatie'] as Doelgroep[],
    checkoutType: 'plan' as CheckoutType,
  },
  {
    title: 'Studytube',
    subtitle: 'Hét LXP/LMS voor de zorg',
    slug: 'studytube',
    type: 'platform' as SolutionType,
    tag: 'Studytube',
    description: 'Het leerplatform dat autonomie bevordert. Medewerkers beheren hun eigen leerpad, kwalificaties en ontwikkeling. Inclusief compliance-dashboard.',
    branches: ['Geestelijke gezondheidszorg', 'Gehandicaptenzorg', 'Thuiszorg', 'Verpleging & Verzorging', 'Ziekenhuis'],
    image: '/images/photos/solution-platform.jpg',
    doelgroepen: ['organisatie'] as Doelgroep[],
    checkoutType: 'plan' as CheckoutType,
  },
  {
    title: 'AskMe',
    subtitle: 'Digitale assistent op de werkvloer',
    slug: 'askme',
    type: 'tool' as SolutionType,
    tag: 'AskMe',
    description: 'Performance support tool die zorgprofessionals direct betrouwbare informatie geeft op het moment dat ze het nodig hebben. Binnen 3 klikken een antwoord.',
    branches: ['Thuiszorg', 'Verpleging & Verzorging', 'Ziekenhuis'],
    image: '/images/photos/solution-tool.jpg',
    doelgroepen: ['professional'] as Doelgroep[],
    checkoutType: 'subscription' as CheckoutType,
  },
  {
    title: 'Assessor',
    subtitle: 'Toetsen en beoordelen',
    slug: 'assessor',
    type: 'tool' as SolutionType,
    tag: 'Assessor',
    description: 'Digitale toets- en beoordelingstool voor praktijkexamens, kennistoetsen en bekwaamheidsverklaringen in de zorg.',
    branches: ['Gehandicaptenzorg', 'Thuiszorg', 'Verpleging & Verzorging', 'Ziekenhuis', 'Zorgonderwijs'],
    image: '/images/photos/care-team-portrait.jpg',
    doelgroepen: ['professional', 'student'] as Doelgroep[],
    checkoutType: 'plan' as CheckoutType,
  },
  {
    title: 'Microlearning',
    subtitle: 'Hapklare kennisbrokken',
    slug: 'microlearning',
    type: 'e-learning' as SolutionType,
    tag: 'Microlearning',
    description: 'Korte, gerichte leermodules met één leerdoel. Ideaal om kennis op te frissen direct op de werkvloer, zoals microleertrajecten Psychiatrische ziektebeelden.',
    branches: ['Geestelijke gezondheidszorg', 'Gehandicaptenzorg', 'Thuiszorg', 'Verpleging & Verzorging'],
    image: '/images/photos/care-medication-box.jpg',
    doelgroepen: ['professional', 'student'] as Doelgroep[],
    checkoutType: 'subscription' as CheckoutType,
  },
  {
    title: 'Leerstrategie',
    subtitle: 'Van visie naar leercultuur',
    slug: 'leerstrategie',
    type: 'consultancy' as SolutionType,
    tag: 'Consultancy',
    description: 'Samen met onze consultants ontwikkel je een leerstrategie die past bij jouw organisatie, medewerkers en doelen.',
    branches: ['Geestelijke gezondheidszorg', 'Gehandicaptenzorg', 'Thuiszorg', 'Verpleging & Verzorging', 'Ziekenhuis'],
    image: '/images/photos/solution-consultancy.jpg',
    doelgroepen: ['organisatie'] as Doelgroep[],
    checkoutType: 'contact' as CheckoutType,
  },
  {
    title: 'Organisatieadvies',
    subtitle: 'Advies op maat',
    slug: 'organisatieadvies',
    type: 'consultancy' as SolutionType,
    tag: 'Consultancy',
    description: 'Onze adviseurs uit de zorg helpen bij het optimaliseren van je leeraanbod, compliance en kwaliteitsmanagement.',
    branches: ['Geestelijke gezondheidszorg', 'Gehandicaptenzorg', 'Thuiszorg', 'Verpleging & Verzorging', 'Ziekenhuis'],
    image: '/images/photos/care-conversation.jpg',
    doelgroepen: ['organisatie'] as Doelgroep[],
    checkoutType: 'contact' as CheckoutType,
  },
  {
    title: 'Product Implementatie',
    subtitle: 'Van kick-off tot adoptie',
    slug: 'product-implementatie',
    type: 'consultancy' as SolutionType,
    tag: 'Consultancy',
    description: 'Begeleiding bij de implementatie van Floren-producten. Van technische inrichting tot het trainen van key-users en ambassadeurs.',
    branches: ['Geestelijke gezondheidszorg', 'Gehandicaptenzorg', 'Thuiszorg', 'Verpleging & Verzorging', 'Ziekenhuis'],
    image: '/images/photos/care-standing-together.jpg',
    doelgroepen: ['organisatie'] as Doelgroep[],
    checkoutType: 'contact' as CheckoutType,
  },
  {
    title: 'Protocollen',
    subtitle: 'Profportaal Zorg',
    slug: 'protocollen',
    type: 'tool' as SolutionType,
    tag: 'Protocollen',
    description: 'Altijd actuele protocollen en richtlijnen via Profportaal Zorg. Afgestemd op Evidence-Based Practice en nationale standaarden.',
    branches: ['Thuiszorg', 'Verpleging & Verzorging', 'Ziekenhuis'],
    image: '/images/photos/care-inhaler-demo.jpg',
    doelgroepen: ['professional'] as Doelgroep[],
    checkoutType: 'subscription' as CheckoutType,
  },
  {
    title: 'Psy Expert',
    subtitle: 'Leeroplossing voor de psychiatrie',
    slug: 'psy-expert',
    type: 'e-learning' as SolutionType,
    tag: 'Psy Expert',
    description: 'Breng leren, ontwikkelen en praktijk samen in één leeroplossing die past bij de zorg. Ondersteun professionals bij hun dagelijkse groei, versterk de teamdynamiek en zorg dat de organisatie altijd voorbereid is op de uitdagingen van morgen.',
    branches: ['Geestelijke gezondheidszorg', 'Ziekenhuis', 'Verpleging & Verzorging'],
    image: '/images/photos/psy-gesprek-1.jpg',
    doelgroepen: ['professional', 'organisatie'] as Doelgroep[],
    checkoutType: 'subscription' as CheckoutType,
    pdp: {
      results: [
        { label: 'RESULTAAT 01', title: 'Snelle Onboarding', description: 'Nieuwe medewerkers voelen zich sneller thuis en bekwaam door een gestructureerd en warm welkom-programma.' },
        { label: 'RESULTAAT 02', title: 'Continue Ontwikkeling', description: 'Blijf voldoen aan wet- en regelgeving terwijl je tegelijkertijd talent stimuleert en door laat groeien.' },
        { label: 'RESULTAAT 03', title: 'Centrale Omgeving', description: 'Geen versnipperde informatie meer. Alle protocollen, cursussen en toetsen op één betrouwbare plek.' },
        { label: 'RESULTAAT 04', title: 'Schaalbaar', description: 'Of je nu een kleine instelling bent of een grote organisatie, de oplossing groeit moeiteloos met je mee.' },
      ],
      audiences: [
        { title: 'Organisaties', description: 'Zorgstellingen die grip willen op kwaliteit en de duurzame inzetbaarheid van hun personeel.', image: '/images/photos/psy-gesprek-2.jpg' },
        { title: 'Leidinggevenden & Opleiders', description: 'Begeleiders die hun teams willen inspireren en de administratieve last van scholing willen verlichten.', image: '/images/photos/psy-gesprek-3.jpg' },
        { title: 'Professionals', description: 'Zorgverleners die op een laagdrempelige manier hun kennis up-to-date willen houden.', image: '/images/photos/psy-gesprek-4.jpg' },
      ],
      features: [
        { icon: 'leerpaden', title: 'Leerpaden', description: 'Structureer complexe opleidingen in behapbare stappen.' },
        { icon: 'inzicht', title: 'Inzicht', description: 'Analyseer data over voortgang en resultaten.' },
        { icon: 'bibliotheek', title: 'Bibliotheek', description: 'Eén start aan content, direct beschikbaar voor alle gebruikers.' },
        { icon: 'onboarding', title: 'Onboarding', description: 'Maak een vliegende start voor elke nieuwe collega.' },
        { icon: 'rapportages', title: 'Rapportages', description: 'Gecertificeerde verslagen voor kwaliteitsindicatoren.' },
        { icon: 'koppeling', title: 'Koppeling', description: 'Integratie met bestaande HR- en zorgsystemen.' },
      ],
      whyFloren: [
        'Deze zorgexpertise: Wij spreken de taal van de zorg en begrijpen de dagelijkse werkdruk.',
        'Didactisch meesterschap: Onze oplossingen zijn gebaseerd op bewezen effectieve leermethoden.',
        'Persoonlijke begeleiding: Van implementatie tot nazorg, wij staan zij-aan-zij met jouw organisatie.',
      ],
      testimonial: {
        quote: 'Sinds we de leeroplossing van Floren gebruiken, hebben we eindelijk echt grip op de ontwikkeling van onze teams. Het is intuïtief, warm en sluit perfect aan bij wat onze zorgverleners nodig hebben.',
        author: 'Hoofd Opleidingen',
        org: 'Zorggroepinstantie Florahealth',
      },
      resources: [
        { type: 'Brochure', title: 'Download de volledige specificaties en mogelijkheden in PDF.', href: '#' },
        { type: 'Praktijkcase', title: 'Lees hoe andere organisaties Floren succesvol hebben geïmplementeerd.', href: '/cases' },
        { type: 'Onderzoek', title: 'Bekijk de impact van digitaal leren op de kwaliteit van zorg.', href: '/artikelen' },
      ],
      faq: [
        { q: 'Is de oplossing geschikt voor mijn type zorginstelling?', a: 'Zeker! Floren is ontworpen als flexibel en past. Of je nu werkt in de V&V, GGZ, GHZ of het ziekenhuis, de modules en leerpaden kunnen volledig worden aangepast aan jullie specifieke zorgpaden en protocollen.' },
        { q: 'Hoe ziet een implementatietraject eruit?', a: 'Na een intake en behoefteanalyse stellen we een implementatieplan op. We begeleiden je van technische inrichting tot het trainen van key-users, met tussentijdse evaluatiemomenten.' },
        { q: 'Kan ik eigen content combineren met Floren-aanbod?', a: 'Ja, dat kan. Je kunt eigen materialen uploaden en combineren met het Floren-aanbod. Zo ontstaat een hybride leeromgeving die perfect past bij jouw organisatie.' },
        { q: 'Ondersteunt Floren ook onboarding van ZZP\'ers?', a: 'Zeker. ZZP\'ers en flexkrachten kunnen snel en eenvoudig worden onboarded met een aangepast programma, zodat zij direct inzetbaar zijn.' },
        { q: 'Hoe kan ik een demo aanvragen?', a: 'Klik op de knop \'Vraag een gesprek aan\' bovenaan deze pagina of ga naar onze demopagina om direct een afspraak in te plannen.' },
      ],
      stats: [
        { value: '85%', label: 'Snellere Onboarding' },
        { value: '100%', label: 'Toetsvalidering' },
        { value: '1', label: 'Centrale Omgeving' },
        { value: 'Flex', label: 'Schaalbaar' },
      ],
    },
  },
]

export const branchCategories = [
  { key: 'alle', label: 'Alle' },
  { key: 'cure', label: 'Cure' },
  { key: 'care', label: 'Care' },
  { key: 'onderwijs', label: 'Onderwijs' },
] as const

export const solutionTypes = [
  { key: 'alle', label: 'Alle' },
  { key: 'e-learning', label: 'E-learning' },
  { key: 'platform', label: 'Platform' },
  { key: 'tool', label: 'Tool' },
  { key: 'consultancy', label: 'Consultancy' },
] as const

// Experts / Consultants
export const experts = [
  {
    name: 'Marieke van den Berg',
    slug: 'marieke-van-den-berg',
    role: 'Senior Consultant Leren & Ontwikkelen',
    specialisatie: ['GGZ', 'Leerstrategie', 'Implementatie'],
    bio: 'Marieke heeft meer dan 15 jaar ervaring in leren en ontwikkelen binnen de GGZ. Ze begeleidt organisaties bij het opzetten van een duurzame leercultuur en de implementatie van digitale leeroplossingen.',
    email: 'm.vandenberg@floren.nl',
    linkedIn: '#',
    image: '/images/photos/consultant-1.jpg',
  },
  {
    name: 'Jeroen Bakker',
    slug: 'jeroen-bakker',
    role: 'Consultant Zorgonderwijs',
    specialisatie: ['Zorgonderwijs', 'MBO', 'Toetsing'],
    bio: 'Jeroen is specialist in zorgonderwijs en helpt ROC\'s en hogescholen bij het integreren van praktijkgerichte e-learning in hun curriculum. Hij is betrokken bij de ontwikkeling van Assessor.',
    email: 'j.bakker@floren.nl',
    linkedIn: '#',
    image: '/images/photos/consultant-2.jpg',
  },
  {
    name: 'Fatima El Amrani',
    slug: 'fatima-el-amrani',
    role: 'Lead Consultant Implementatie',
    specialisatie: ['V&V', 'Thuiszorg', 'Product Implementatie'],
    bio: 'Fatima begeleidt zorginstellingen van kick-off tot volledige adoptie. Met haar achtergrond als verpleegkundige snapt ze de uitdagingen op de werkvloer als geen ander.',
    email: 'f.elamrani@floren.nl',
    linkedIn: '#',
    image: '/images/photos/consultant-3.jpg',
  },
  {
    name: 'Dr. Peter Visser',
    slug: 'peter-visser',
    role: 'Inhoudelijk Expert & Auteur',
    specialisatie: ['Evidence-Based Practice', 'Protocollen', 'Klinisch redeneren'],
    bio: 'Peter is gepromoveerd in de verplegingswetenschappen en verantwoordelijk voor de inhoudelijke kwaliteit van Floren\'s leermateriaal. Hij schrijft artikelen over evidence-based leren in de zorg.',
    email: 'p.visser@floren.nl',
    linkedIn: '#',
    image: '/images/photos/consultant-4.jpg',
  },
  {
    name: 'Sophie de Groot',
    slug: 'sophie-de-groot',
    role: 'Consultant Digitaal Leren',
    specialisatie: ['Ziekenhuis', 'Microlearning', 'Studytube'],
    bio: 'Sophie helpt ziekenhuizen en MSZ-organisaties bij het optimaliseren van hun digitale leeromgeving. Ze is expert op het gebied van microlearning en blended learning.',
    email: 's.degroot@floren.nl',
    linkedIn: '#',
    image: '/images/photos/consultant-5.jpg',
  },
]

// Artikelen / Content
export const artikelen = [
  {
    title: 'Hoe microlearning de borging van kennis verbetert in de GGZ',
    slug: 'microlearning-borging-ggz',
    date: '2026-05-14',
    category: 'Kennisartikel',
    readTime: '6 min',
    author: 'peter-visser',
    excerpt: 'Onderzoek toont aan dat korte, herhaalde leermomenten effectiever zijn dan lange trainingen. Hoe pas je dit toe in de GGZ?',
    branches: ['GGZ'],
    content: `De GGZ staat voor unieke uitdagingen als het gaat om bijscholing. Medewerkers werken met complexe casuïstiek en moeten voortdurend op de hoogte blijven van nieuwe inzichten en richtlijnen.\n\nMicrolearning biedt een oplossing: korte modules van 5-10 minuten, gericht op één leerdoel, die direct toepasbaar zijn in de praktijk. Uit recent onderzoek blijkt dat deze aanpak de kennisretentie met 40% verbetert ten opzichte van traditionele klassikale trainingen.\n\nBij Floren hebben we dit principe verwerkt in onze Microlearning-modules voor de GGZ. Denk aan hapklare lessen over psychiatrische ziektebeelden, motiverende gespreksvoering en medicatieveiligheid.\n\n## De drie pijlers van effectieve microlearning\n\n1. **Relevantie** — De content sluit aan bij dagelijkse casuïstiek\n2. **Herhaling** — Spaced repetition zorgt voor duurzame kennisborging\n3. **Toetsing** — Korte checks bevestigen begrip`,
  },
  {
    title: 'De toekomst van digitaal leren in de thuiszorg',
    slug: 'digitaal-leren-thuiszorg',
    date: '2026-04-28',
    category: 'Trendanalyse',
    readTime: '8 min',
    author: 'fatima-el-amrani',
    excerpt: 'Thuiszorgmedewerkers werken zelfstandig en verspreid. Hoe bereik je ze met effectieve scholing?',
    branches: ['Thuiszorg'],
    content: `De thuiszorg is een van de snelst groeiende sectoren in de Nederlandse gezondheidszorg. Met een toenemend personeelstekort en een stijgende zorgvraag is het cruciaal dat medewerkers efficiënt en effectief worden bijgeschoold.\n\nDigitaal leren biedt hier enorme kansen. Thuiszorgmedewerkers kunnen in hun eigen tempo leren, op momenten die hen uitkomen. Tools als AskMe bieden daarnaast directe ondersteuning op de werkvloer.\n\n## Uitdagingen in de thuiszorg\n\nDe grootste uitdaging is bereikbaarheid. Medewerkers zitten niet achter een bureau, maar zijn onderweg tussen cliënten. Mobiel leren is daarom essentieel.\n\n## Onze aanpak\n\nMet ZorgPad Professional en Studytube bieden we een compleet digitaal leerplatform dat optimaal werkt op mobiele devices.`,
  },
  {
    title: 'Implementatie van e-learning: 5 lessen uit de praktijk',
    slug: 'implementatie-lessen-praktijk',
    date: '2026-04-10',
    category: 'Best practice',
    readTime: '5 min',
    author: 'marieke-van-den-berg',
    excerpt: 'Een goed product is pas de helft van het verhaal. De implementatie bepaalt het succes. Dit zijn onze vijf belangrijkste lessen.',
    branches: ['GGZ', 'V&V', 'Ziekenhuis'],
    content: `Na honderden implementaties bij zorginstellingen door heel Nederland hebben we vijf cruciale lessen geleerd die het verschil maken tussen een succesvolle uitrol en een digitaal stofnest.\n\n## 1. Begin met ambassadeurs\n\nIdentificeer enthousiaste medewerkers die als ambassadeur kunnen fungeren. Zij zijn de motor van adoptie op de werkvloer.\n\n## 2. Maak het persoonlijk\n\nKoppel het leeraanbod aan de dagelijkse praktijk van de medewerker. Relevantie is de sleutel tot motivatie.\n\n## 3. Meet en communiceer\n\nGebruik dashboards om voortgang inzichtelijk te maken en deel successen met het team.\n\n## 4. Bied ondersteuning\n\nZorg voor een helpdesk en train key-users die collega\'s kunnen helpen.\n\n## 5. Evalueer en optimaliseer\n\nPlan evaluatiemomenten in en pas het aanbod aan op basis van feedback.`,
  },
  {
    title: 'Assessor: digitaal toetsen in het zorgonderwijs',
    slug: 'assessor-digitaal-toetsen',
    date: '2026-03-22',
    category: 'Productverdieping',
    readTime: '4 min',
    author: 'jeroen-bakker',
    excerpt: 'Hoe ROC\'s en hogescholen Assessor inzetten voor betrouwbare, efficiënte toetsing van zorgstudenten.',
    branches: ['Zorgonderwijs'],
    content: `Toetsing in het zorgonderwijs is complex. Studenten moeten niet alleen theoretische kennis aantonen, maar ook praktische vaardigheden en professioneel gedrag.\n\nAssessor is ontwikkeld om dit proces te digitaliseren en te stroomlijnen. Van kennistoetsen tot praktijkbeoordelingen en bekwaamheidsverklaringen — alles in één systeem.\n\n## Voordelen van digitaal toetsen\n\n- **Betrouwbaarder** — Gestandaardiseerde criteria en rubrics\n- **Efficiënter** — Minder administratie voor docenten\n- **Inzichtelijker** — Realtime rapportages over studentprestaties\n\n## Integratie met het curriculum\n\nAssessor integreert naadloos met bestaande onderwijssystemen via LTI-koppelingen.`,
  },
]

// Cases
export const cases = [
  {
    title: 'GGZ Rivierduinen: 80% adoptie in 3 maanden',
    slug: 'ggz-rivierduinen',
    client: 'GGZ Rivierduinen',
    branche: 'GGZ',
    excerpt: 'Hoe GGZ Rivierduinen met ZorgPad Professional en een gerichte implementatiestrategie 80% adoptie bereikte.',
    result: '80% adoptie',
    consultant: 'marieke-van-den-berg',
  },
  {
    title: 'Thuiszorg Groningen: mobiel leren op de fiets',
    slug: 'thuiszorg-groningen',
    client: 'Thuiszorg Groningen',
    branche: 'Thuiszorg',
    excerpt: 'Thuiszorg Groningen zocht een manier om verspreid werkende medewerkers bij te scholen. Met Studytube en microlearning lukte dat.',
    result: '95% tevredenheid',
    consultant: 'fatima-el-amrani',
  },
  {
    title: 'ROC Midden Nederland: Assessor in het curriculum',
    slug: 'roc-midden-nederland',
    client: 'ROC Midden Nederland',
    branche: 'Zorgonderwijs',
    excerpt: 'Dit ROC integreert Assessor in alle zorgopleidingen voor betrouwbare, digitale toetsing.',
    result: '40% minder administratie',
    consultant: 'jeroen-bakker',
  },
]
